<a href="https://colab.research.google.com/github/SinghReena/MachineLearning/blob/master/Imputing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame({"col1" : [10, 20, np.nan, 50, 25],
                  "col2" : [1, np.nan, 5, 7, 8],
                  "col3" : [np.nan, 5, 7, 5, 6] })
df

col1  col2  col3
0  10.0   1.0   NaN
1  20.0   NaN   5.0
2   NaN   5.0   7.0
3  50.0   7.0   5.0
4  25.0   8.0   6.0

In [ ]:
from sklearn.impute import SimpleImputer

imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit_transform(df)

array([[10.  ,  1.  ,  5.75],
       [20.  ,  5.25,  5.  ],
       [26.25,  5.  ,  7.  ],
       [50.  ,  7.  ,  5.  ],
       [25.  ,  8.  ,  6.  ]])

In [ ]:
df

col1  col2  col3
0  10.0   1.0   NaN
1  20.0   NaN   5.0
2   NaN   5.0   7.0
3  50.0   7.0   5.0
4  25.0   8.0   6.0

In [ ]:
imp_mode = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imp_mode.fit_transform(df)

array([[10.,  1.,  5.],
       [20.,  1.,  5.],
       [10.,  5.,  7.],
       [50.,  7.,  5.],
       [25.,  8.,  6.]])

In [ ]:
from sklearn.compose import make_column_transformer

ct = make_column_transformer(
    (imp_mean, ['col1', ]), 
    ('passthrough', ['col2']),
    (imp_mode, ['col3'])
    )
ct.fit_transform(df)

array([[10.  ,  1.  ,  5.  ],
       [20.  ,   nan,  5.  ],
       [26.25,  5.  ,  7.  ],
       [50.  ,  7.  ,  5.  ],
       [25.  ,  8.  ,  6.  ]])