<a href="https://colab.research.google.com/github/SinghReena/MachineLearning/blob/master/Numpy_exercises_Solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

The problems are slightly modified from the quest

In [ ]:
import numpy as np


1. Create a null vector of size 10 but the fifth value which is 1

In [ ]:
n_v=np.full(10,None)
n_v[4]=1

2. Reverse a vector (first element becomes last)



In [ ]:
r_v=np.arange(10)
r_v[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

3. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
a=np.arange(9).reshape(3,3)
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

4. Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

5. Create a 3x3x3 array with random values 

In [ ]:
b = np.random.randint(1,20,9).reshape(3,3)
b

array([[15,  6,  2],
       [14,  5, 16],
       [11,  6,  5]])

6. Create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
b = np.random.random(100).reshape(10,10)
print(np.min(b))
b


0.007230740911720823


array([[0.93246273, 0.75882134, 0.06867799, 0.19174313, 0.91489193,
        0.40735661, 0.53584492, 0.26557534, 0.04189668, 0.87830396],
       [0.9008303 , 0.60429073, 0.41457156, 0.16973555, 0.12225181,
        0.56699825, 0.00723074, 0.81472553, 0.59974928, 0.75127922],
       [0.04455584, 0.23478309, 0.75825334, 0.73042366, 0.2456459 ,
        0.44058106, 0.89079845, 0.06626944, 0.77263704, 0.62333596],
       [0.66724595, 0.14718279, 0.44227117, 0.54389517, 0.38704606,
        0.94450171, 0.99385397, 0.76884997, 0.45198839, 0.49029192],
       [0.87904323, 0.93740957, 0.40579549, 0.0451919 , 0.99275423,
        0.25665221, 0.25620815, 0.33607675, 0.27755437, 0.58478181],
       [0.02498998, 0.58123261, 0.76614975, 0.1639322 , 0.51612024,
        0.86921195, 0.26288159, 0.09093141, 0.68096074, 0.11157445],
       [0.31497674, 0.27766242, 0.35181406, 0.65492286, 0.01390918,
        0.12563436, 0.025375  , 0.16540615, 0.14509705, 0.95758673],
       [0.06388206, 0.48522911, 0.2205671

7. Create a 2d array with 1 on the border and 0 inside

In [ ]:
c=np.zeros((5,5))
c[0,:]=1
c[:,0]=1
c[-1,:]=1
c[:,-1]=1
c 

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

8. How to round a float array to use only the integer part?

Hint:  Find the right function from https://numpy.org/doc/stable/reference/routines.math.html

In [ ]:
a=np.array([4.1, 5.8, 3.0, -5.4, -3.6])
np.round(a,0)


array([ 4.,  6.,  3., -5., -4.])

In [ ]:
np.trunc(a)

array([ 4.,  5.,  3., -5., -3.])

9. Consider two random array A and B, check if they are equal

Hint: Find the right function in https://numpy.org/doc/stable/reference/routines.logic.html#comparison


In [ ]:
np.array_equal(a,b)

False